// <auto-generated />
using System;
using BackEndProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEndProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220724183714_addDatasWithSeed")]
    partial class addDatasWithSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEndProject.Models.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "images/banner-1.png"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "images/banner-2.png"
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId1");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("BackEndProject.Models.Bio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bios");
                });

            modelBuilder.Entity("BackEndProject.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget dui rhoncus, malesuada lectus vel, rhoncus felis. Suspendisse nec tempor nunc, non maximus lacus.",
                            ImageUrl = "images/blog-1.jpg",
                            Time = new DateTime(2022, 7, 24, 22, 37, 13, 688, DateTimeKind.Local).AddTicks(6052),
                            Title = "This is first blog"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget dui rhoncus, malesuada lectus vel, rhoncus felis. Suspendisse nec tempor nunc, non maximus lacus.",
                            ImageUrl = "images/blog-2.jpg",
                            Time = new DateTime(2022, 7, 24, 22, 37, 13, 688, DateTimeKind.Local).AddTicks(6904),
                            Title = "This is second blog"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget dui rhoncus, malesuada lectus vel, rhoncus felis. Suspendisse nec tempor nunc, non maximus lacus.",
                            ImageUrl = "images/blog-3.jpg",
                            Time = new DateTime(2022, 7, 24, 22, 37, 13, 688, DateTimeKind.Local).AddTicks(6980),
                            Title = "This is third blog"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget dui rhoncus, malesuada lectus vel, rhoncus felis. Suspendisse nec tempor nunc, non maximus lacus.",
                            ImageUrl = "images/blog-4.jpg",
                            Time = new DateTime(2022, 7, 24, 22, 37, 13, 688, DateTimeKind.Local).AddTicks(7028),
                            Title = "This is fourth blog"
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UptadetAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 682, DateTimeKind.Local).AddTicks(2632),
                            ImageUrl = "images/brand/brand-1.jpg",
                            IsDeleted = false,
                            Name = "Nokia"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(6716),
                            ImageUrl = "images/brand/brand-2.jpg",
                            IsDeleted = false,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(6969),
                            ImageUrl = "images/brand/brand-3.jpg",
                            IsDeleted = false,
                            Name = "HTC"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(7050),
                            ImageUrl = "images/brand/brand-4.jpg",
                            IsDeleted = false,
                            Name = "Xioami"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(7105),
                            ImageUrl = "images/brand/brand-5.jpg",
                            IsDeleted = false,
                            Name = "Hoffmann"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(7169),
                            ImageUrl = "images/brand/brand-6.jpg",
                            IsDeleted = false,
                            Name = "Delonghi"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(7218),
                            ImageUrl = "images/brand/brand-1.jpg",
                            IsDeleted = false,
                            Name = "Gorenji"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(7268),
                            ImageUrl = "images/brand/brand-2.jpg",
                            IsDeleted = false,
                            Name = "Toshiba"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(7316),
                            ImageUrl = "images/brand/brand-4.jpg",
                            IsDeleted = false,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 685, DateTimeKind.Local).AddTicks(7369),
                            ImageUrl = "images/brand/brand-3.jpg",
                            IsDeleted = false,
                            Name = "Dell"
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UptadetAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(6402),
                            ImageUrl = "images/category-2.jpg",
                            IsDeleted = false,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8196),
                            ImageUrl = "images/category-1.jpg",
                            IsDeleted = false,
                            Name = "Laptop",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8337),
                            ImageUrl = "images/category-3.jpg",
                            IsDeleted = false,
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8393),
                            ImageUrl = "images/category-4.jpg",
                            IsDeleted = false,
                            Name = "Game Consoles"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8443),
                            ImageUrl = "images/category-5.jpg",
                            IsDeleted = false,
                            Name = "Bottoms"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8501),
                            ImageUrl = "images/category-6.jpg",
                            IsDeleted = false,
                            Name = "Tops & Sets"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8549),
                            ImageUrl = "images/category-7.jpg",
                            IsDeleted = false,
                            Name = "Audio & Video"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8618),
                            ImageUrl = "images/category-10.jpg",
                            IsDeleted = false,
                            Name = "Camera",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8674),
                            ImageUrl = "images/category-9.jpg",
                            IsDeleted = false,
                            Name = "Household"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8727),
                            ImageUrl = "images/category-8.jpg",
                            IsDeleted = false,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8793),
                            ImageUrl = "images/category-11.jpg",
                            IsDeleted = false,
                            Name = "Michrophone",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8844),
                            ImageUrl = "images/category-12.jpg",
                            IsDeleted = false,
                            Name = "Video Games",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 686, DateTimeKind.Local).AddTicks(8893),
                            ImageUrl = "images/category-1.jpg",
                            IsDeleted = false,
                            Name = "Technologics"
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.DeliveryBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryBans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Every third product",
                            ImageUrl = "images/banner-icon/icon1.png",
                            Title = "Free Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "24/7",
                            ImageUrl = "images/banner-icon/icon2.png",
                            Title = "Delivery"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "24hour delivery",
                            ImageUrl = "images/banner-icon/icon3.png",
                            Title = "GoturApar Delivery"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "Stay at home delivery",
                            ImageUrl = "images/banner-icon/icon4.png",
                            Title = "Gelme Getiririk Delivery"
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BackEndProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BackEndProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BestSeller")
                        .HasColumnType("bit");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NewArrival")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.Property<double>("TaxPercent")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UptadetAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestSeller = false,
                            BrandId = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(133),
                            DiscountPrice = 30.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Joystic Logitech g66",
                            NewArrival = true,
                            Price = 900.0,
                            StockCount = 33,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 2,
                            BestSeller = true,
                            BrandId = 5,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6229),
                            DiscountPrice = 30.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Airpods Pro",
                            NewArrival = false,
                            Price = 250.0,
                            StockCount = 30,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 3,
                            BestSeller = false,
                            BrandId = 4,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6431),
                            DiscountPrice = 0.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "HDD",
                            NewArrival = false,
                            Price = 75.0,
                            StockCount = 25,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 4,
                            BestSeller = true,
                            BrandId = 2,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6496),
                            DiscountPrice = 0.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Printer",
                            NewArrival = true,
                            Price = 300.0,
                            StockCount = 25,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 5,
                            BestSeller = false,
                            BrandId = 2,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6556),
                            DiscountPrice = 0.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Go Pro Max",
                            NewArrival = true,
                            Price = 3000.0,
                            StockCount = 9,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 6,
                            BestSeller = true,
                            BrandId = 1,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6621),
                            DiscountPrice = 0.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Glasses",
                            NewArrival = false,
                            Price = 99.0,
                            StockCount = 800,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 7,
                            BestSeller = false,
                            BrandId = 3,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6680),
                            DiscountPrice = 0.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Insta360",
                            NewArrival = false,
                            Price = 199.0,
                            StockCount = 75,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 8,
                            BestSeller = false,
                            BrandId = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6737),
                            DiscountPrice = 0.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "MiPods",
                            NewArrival = true,
                            Price = 900.0,
                            StockCount = 75,
                            TaxPercent = 0.0
                        },
                        new
                        {
                            Id = 9,
                            BestSeller = true,
                            BrandId = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 7, 24, 22, 37, 13, 687, DateTimeKind.Local).AddTicks(6794),
                            DiscountPrice = 0.0,
                            InStock = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Zenbook",
                            NewArrival = false,
                            Price = 5000.0,
                            StockCount = 39,
                            TaxPercent = 0.0
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "images/product/product-3.jpg",
                            IsMain = true,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "images/product/product-9.jpg",
                            IsMain = false,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "images/product/product-1.jpg",
                            IsMain = true,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "images/product/product-2.jpg",
                            IsMain = false,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "images/product/product-5.jpg",
                            IsMain = true,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "images/product/product-6.jpg",
                            IsMain = false,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "images/product/product-14.jpg",
                            IsMain = true,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "images/product/product-15.jpg",
                            IsMain = false,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "images/product/product-8.jpg",
                            IsMain = true,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "images/product/product-7.jpg",
                            IsMain = false,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "images/product/product-13.jpg",
                            IsMain = true,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "images/product/product-12.jpg",
                            IsMain = false,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "images/product/product-10.jpg",
                            IsMain = true,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "images/product/product-11.jpg",
                            IsMain = false,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "images/category-3.jpg",
                            IsMain = true,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "images/product/product-11.jpg",
                            IsMain = false,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "images/category-1.jpg",
                            IsMain = true,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "images/category-6.jpg",
                            IsMain = false,
                            ProductId = 9
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountSec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Explore and immerse in exciting 360 content with Fulldive’s all-in-one virtual reality platform",
                            DiscountSec = "Save $120 when you buy",
                            ImageUrl = "images/slider-1.jpg",
                            Title = "2020 Virtual Reality"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Explore and immerse in exciting 360 content with Fulldive’s all-in-one virtual reality platform",
                            DiscountSec = "Save $120 when you buy",
                            ImageUrl = "images/slider-2.jpg",
                            Title = "4K HDR Smart TV 43"
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BackEndProject.Models.TagProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("TagProducts");
                });

            modelBuilder.Entity("BackEndProject.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorEmail = "murad@gmail.com",
                            AuthorName = "Murad",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "images/author-1.png"
                        },
                        new
                        {
                            Id = 2,
                            AuthorEmail = "azad@gmail.ru",
                            AuthorName = "Azad",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "images/author-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AuthorEmail = "anar@gmail.ru",
                            AuthorName = "Anar",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "images/author-3.jpg"
                        });
                });

            modelBuilder.Entity("BackEndProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BackEndProject.Models.BasketItem", b =>
                {
                    b.HasOne("BackEndProject.Models.Product", "Product")
                        .WithMany("BasketItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndProject.Models.User", "User")
                        .WithMany("BasketItems")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("BackEndProject.Models.Order", b =>
                {
                    b.HasOne("BackEndProject.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("BackEndProject.Models.OrderItem", b =>
                {
                    b.HasOne("BackEndProject.Models.Product", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndProject.Models.Product", b =>
                {
                    b.HasOne("BackEndProject.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndProject.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndProject.Models.ProductImage", b =>
                {
                    b.HasOne("BackEndProject.Models.Product", "product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndProject.Models.TagProduct", b =>
                {
                    b.HasOne("BackEndProject.Models.Product", null)
                        .WithMany("TagProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
